#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "games"
OUTPUT = ROOT / "SUMMARY.md"

def esc(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

def render():
    lines = [
        "# Readbacks evidence summary",
        "",
        "<!-- Generated by tools/generate_summary.py. Do not edit manually. -->",
        "",
        "A row is one evidence-backed claim, not a universal per-game setting.",
        "",
        "| Game | Serial | shadPS4 | Scope | Finding | Confidence | Observation | Evidence |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for path in sorted(DATA.glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        for claim in record["claims"]:
            version = claim["shadps4_version"] or "—"
            finding = f"{claim['mode'].title()} {claim['finding'].replace('_', ' ')}"
            evidence = claim["evidence"][0]["url"]
            lines.append(
                "| " + " | ".join([
                    esc(record["title"]),
                    esc(record["serial"]),
                    esc(version),
                    esc(claim["scope"].replace("_", " ")),
                    esc(finding),
                    esc(claim["confidence"]),
                    esc(claim["summary"]),
                    f"[source]({evidence})",
                ]) + " |"
            )
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("SUMMARY.md is stale; run: python3 tools/generate_summary.py", file=sys.stderr)
            return 1
        print("OK: SUMMARY.md is up to date")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
